# Generated by Django 2.0.2 on 2018-02-11 18:59

from django.db import migrations, models
import django.db.models.deletion

import csv


def import_data_from_csv(apps, schema_editor):
    Symptom = apps.get_model("app", "Symptom")
    Diagnosis = apps.get_model("app", "Diagnosis")
    reader = csv.reader(open("../symptoms.csv"), dialect='excel')
    print('test')
    for row in reader:
       print(row)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Symptom'),
        ),
        migrations.RunPython(import_data_from_csv),
    ]
